### ISSUE TITLE
`.mix` folder is not created at building

### ISSUE THREAD

**Issue by nallwhy** [kipcole9/cldr#112]
elixir version: 1.8.1
ex_cldr version: 1.8.2

error message:
```
Generated my_project app
** (File.Error) could not write to file "/Users/me/workspace/project/my_project/_build/dev/.mix/.compile.cldr": no such file or directory
    (elixir) lib/file.ex:1014: File.write!/3
    lib/mix/tasks/compile.cldr.ex:288: Mix.Tasks.Compile.Cldr.previous_locales/0
    lib/mix/tasks/compile.cldr.ex:61: Mix.Tasks.Compile.Cldr.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (elixir) lib/file.ex:1506: File.cd!/2
    (mix) lib/mix/project_stack.ex:41: Mix.ProjectStack.on_recursing_root/1
    (mix) lib/mix/tasks/compile.all.ex:68: Mix.Tasks.Compile.All.run_compiler/2
    (mix) lib/mix/tasks/compile.all.ex:52: Mix.Tasks.Compile.All.do_compile/4
```

It is fixed by creating `.mix` folder manually, but I want to know the reason of this problem.

**Comment by kipcole9** [comment]
I suspect this is a result of a different Elixir compiler environment in Elixir 1.8 (different from Elixir 1.7). Cldr 1.x libraries are replaced with the Cldr 2.x libraries which I recommend with one exception.  If you need `ex_cldr_dates_times` then that is not yet at 2.x release.

Cldr 2.x is a major refactoring that solves many issues from the build environment of Cldr 1.x so if at all possible I recommend you upgrade. There are some breaking changes, primarily around configuration, but I think it is worth the modest effort.

If you do need `ex_cldr_dates_times` then I am certainly working on this with some urgency now.

Given the current situation, manually creating the `.mix` directory seems the most pragmatic solution.

As a further note, the `elixir compiler` in Cldr 1.x keeps a manifest file to help it detect when locale configuration has changed and therefore to force recompilation. Hence why its trying to find that file in what used to be a standard directory for Elixir in older releases.

**Comment by nallwhy** [comment]
@kipcole9 Thx. It works well.
