### ISSUE TITLE
Doesn't compile

### ISSUE THREAD

**Issue by vraravam** [kipcole9/cldr#12]
I'm trying to incorporate your library `ex_money` into my phoenix app. When I try to compile, this is what I get:
<img width="959" alt="screen shot 2016-12-11 at 5 23 13 am" src="https://cloud.githubusercontent.com/assets/69629/21077007/179718b6-bf62-11e6-9e96-d6c392b43796.png">

Could you please fix asap?

**Comment by kipcole9** [comment]
Vijay, thanks for the report.  The Plug is not complete as you can see so my temporary fix will be to not compile that module at all.  I will have a new version on hex within an hour.

**Comment by kipcole9** [comment]
Vijay, update you deps to `{:ex_cldr, "~>  0.0.13"}` or run `mix deps.update ex_cldr` and you should be good to go.  Note that I have disabled the compilation of `Cldr.Plug` since its not implemented yet.
