### ISSUE TITLE
JSON data read at runtime

### ISSUE THREAD

**Issue by LostKobrakai** [kipcole9/cldr#127]
As mentioned [here](https://github.com/kipcole9/money/pull/103#issuecomment-498045081) `Money.to_string` is currently quite slow and seems to do quite a bit of json reading, which it really shouldn't. The offending code seems to be  
https://github.com/kipcole9/cldr/blob/master/lib/cldr.ex#L1242, which ultimately lands at `Cldr.Config.number_systems`. This seems to be done 4 times per `Money.to_string` in my research.

**Comment by kipcole9** [comment]
@LostKobrakai Thanks for looking into this. Fix with [this commit](https://github.com/kipcole9/cldr/commit/d33c01d86cb01957455a4eb7c70cded08b7f47d2).

Published to hex as [version 2.7.1](https://hex.pm/packages/ex_cldr/2.7.1).

Performance difference is materially different as expected:
```
Version   Name                ips        average  deviation         median         99th %
2.7.0      to_string        334.14        2.99 ms    ±24.62%        2.79 ms        5.41 ms
2.7.1       to_string        8.98 K      111.34 μs    ±29.45%         102 μs         224 μs
```

**Comment by kipcole9** [comment]
> As mentioned [here](https://github.com/kipcole9/money/pull/103#issuecomment-498045081) `Money.to_string` is currently quite slow and seems to do quite a bit of json reading, which it really shouldn't. The offending code seems to be
> https://github.com/kipcole9/cldr/blob/master/lib/cldr.ex#L1242, which ultimately lands at `Cldr.Config.number_systems`. This seems to be done 4 times per `Money.to_string` in my research.

@LostKobrakai May I ask what versions of [ex_cldr_numbers](https://hex.pm/packages/ex_cldr_numbers) you are using?  I did some work a couple of releases ago to remove the need to validate options (like `number_system`) multiple times so I'd like to track this down.

**Comment by kipcole9** [comment]
Hmmm, I profiled again and I see what you observed (and more) on the latest releases.  I'll take a look at this tonight, there's clearly more room for improvement.

**Comment by LostKobrakai** [comment]
I just did a dummy install (so latest version before todays releases) and used `:dbg` to trace up the callstack from `Jason.decode!` by running `Money.to_string` in iex, because I had no idea what code in cldr would even call it :D
