### ISSUE TITLE
Always using international currency symbols

### ISSUE THREAD

**Issue by wojtekmach** [kipcole9/cldr#15]
Hello!
Is this possible to always use international currency symbols (EUR, USD) etc, instead of localized symbols (€, $)? Per the spec it should be left to the application [1].

E.g.: I'd like to be able always represent numbers in the format `123,456.78 EUR` regardless of the locale (however, `,` and `.` would be replaced with appropriate symbols specific to locale)

If it's not currently possible, I'd be happy to give it a shot but I'd probably need some pointers.

PS thank you for this library, it seems it's exactly what we need for our application!

[1] http://cldr.unicode.org/translation/number-patterns, section "General Purpose Numbers"

**Comment by wojtekmach** [comment]
Sorry for the noise, I had wrong test setup and didn't realize passing `format:` solves this nicely:

```elixir
iex> Cldr.Number.to_string(Decimal.new("1234567.8"), format: "#,##0.00") <> " EUR"
"1,234,567.80 EUR"
```

I think it would still be nice to specify the symbol as per the spec, but above workaround should be good enough.

**Comment by kipcole9** [comment]
Wojtek, thats a good ask.  I’ll take a look at the code today, shouldn’t be too much of an issue.

**Comment by kipcole9** [comment]
Wotjek, I wouldn’t recommend that format string.  The currency formats do more than just format the string.  They:

1. Round to the nearest minimum unit (ie. CHF round to the nears 0.05, JPY rounds to the nearest 0.00)
2. Round correctly to the right number of decimal places (using bankers rounding by default)

**Also note that the currency symbol can be inserted in the format string**.  The relevant code is in `Cldr.Number.Formatter.Decimal`:

```elixir
  # Extract the appropriate currency symbol based upon how many currency
  # placeholders are in the format as follows:
  #   ¤      Standard currency symbol
  #   ¤¤     ISO currency symbol (constant)
  #   ¤¤¤    Appropriate currency display name for the currency, based on the
  #          plural rules in effect for the locale
  #   ¤¤¤¤   Narrow currency symbol.
  defp currency_symbol(%Currency{} = currency, _number, 1, _locale) do
    currency.symbol
  end

  defp currency_symbol(%Currency{} = currency, _number, 2, _locale) do
    currency.code
  end

  defp currency_symbol(%Currency{} = currency, number, 3, locale) do
    Number.Cardinal.pluralize(number, locale, currency.count)
  end

  defp currency_symbol(%Currency{} = currency, _number, 4, _locale) do
    currency.narrow_symbol || currency.symbol
  end

  defp currency_symbol(currency, number, size, locale) do
    currency = Currency.for_code(currency, locale)
    currency_symbol(currency, number, size, locale)
  end
```

So if you insert the marker for ISO currency symbol into the format string then I think you’ll get a more standardised result.   Based upon your use case I would suggest:  `"¤¤#,##0.##"`

```elixir
iex(6)> Cldr.Number.to_string(Decimal.new("1234567.8"), format: "¤¤#,##0.##", currency: "EUR") 
"EUR1234,567.80"
```

**Comment by wojtekmach** [comment]
Excellent, thank you!
