### ISSUE TITLE
Support Poison 3.0

### ISSUE THREAD

**Issue by jayjun** [kipcole9/cldr#16]
Most of the libraries I'm using have moved to Poison 3.0+, leaving this package as the last holdout.

Sometimes, both major versions are supported by specifying `"~> 2.2 or ~> 3.0"`, including [Phoenix 1.3](https://github.com/phoenixframework/phoenix/blob/master/mix.exs#L52).

Moreover, [devinus/poison](https://github.com/devinus/poison) doesn't show a 2.0 branch so I'm not even sure if any fixes are backported.

**Comment by kipcole9** [comment]
Updated cldr to version 0.2.0 with dependency `"~> 2.1 or ~> 3.0`.  Also now only runs on Elixir 1.4.  See the change log for other changes -> mostly to do with the first phase of localising dates/datetimes
