### ISSUE TITLE
Issue compiling on windows

### ISSUE THREAD

**Issue by LostKobrakai** [kipcole9/cldr#19]
`Cldr.Install.ensure_client_dirs_exist!` does try to create the following directories on windows:

```
Generating Cldr for 10 locales ["de", "de-AT", "de-BE", "de-CH", "de-IT", ...] with default locale "en"
["/c:", "/Users", "/fklement", "/Desktop", "/connect", "/_build", "/dev",
 "/lib", "/ex_cldr", "/priv", "/cldr", "/locales"]
```

For the following correct path:  `c:/Users/fklement/Desktop/connect/…`

Noticed by @fklement

**Comment by kipcole9** [comment]
Updated on hex as ex_cldr 0.8.1

**Comment by LostKobrakai** [comment]
Cool, so I can update my deps to no longer use my custom branch :D

**Comment by kipcole9** [comment]
You'll want:

ex_cldr 0.8.1
ex_cldr_numbers 0.2.0
ex_money 0.7.0

All the tests are green on Elixir 1.5 and on master so I'm optimistic all is ok; there's been a lot of refactoring going on lately and I'm not quite done yet as I head towards 1.0 by years end.

**Comment by LostKobrakai** [comment]
yeah, I already notices ex_cldr_units being behind, but it's not in any way urgent

**Comment by kipcole9** [comment]
units and lists coming in the next 30 minutes :-)

**Comment by kipcole9** [comment]
ex_cldr_dates_times coming in the next 5 minutes
