### ISSUE TITLE
Conditional inclusion of CLDR components

### ISSUE THREAD

**Issue by kipcole9** [kipcole9/cldr#2]
Cldr consists of a lot of static text, multiplied by up to 511 locales.  Today the number of locales can be configured but not the CLDR components requested.  As more functionality is added, the more the memory footprint will grow.

The idea is to be able to configure in `mix.exs` which components are to be included in an installation.  Something like:

```
config :ex_cldr,
  components: [:number, :currency, :territory, :date]
```

And then conditionally compile those modules into the application.

**Comment by kipcole9** [comment]
Done from ex_cldr version 0.7 onwards.

**Comment by dkuku** [comment]
> Done from ex_cldr version 0.7 onwards.

Hi @kipcole9 . Is this documented somewhere? I can't find it anywhere.

**Comment by kipcole9** [comment]
Basically the whole of the `ex_cldr` from [version 2.0](https://hexdocs.pm/ex_cldr/changelog.html#cldr-v2-0-0) in 2018 is built on this principle. Using the `:providers` [configuration key](https://hexdocs.pm/ex_cldr/readme.html#providers) for a given backend determines which data and functions are encapsulated.

**Comment by kipcole9** [comment]
Does that clarify?

**Comment by dkuku** [comment]
Ok, thanks. I wasn't sure and the code for the version mentioned is not
available anymore, so I could not compare how this was implemented.

**Comment by kipcole9** [comment]
The transition to 2.x was back at the end of 2017 so other than the migration guide in the changelog the past was consigned to history. There is a `v0.7.0` tag in the repo if you're curious but I don't think there is anything to be learned diving that far back.

Happy to answer any questions you might have about architecture or implementation.
