### ISSUE TITLE
Cldr.Plug.Locale - design thoughts

### ISSUE THREAD

**Issue by kipcole9** [kipcole9/cldr#24]
The last functional part to be developed before Cldr version 1.0 is a plug to parse the `accept-language` header and set the locale.  I'm looking for feedback on the following.

There are at least 3 places in an HTTP request to look for a locale
  * `accept-language` header
  * a `locale` parameter like `https://domain.com/content?locale=en`
  * a `locale` segment in an URL like `https://domain.com/en/content`

Should the plug look for a locale in

1. All three by default?  If so, what precedence?
2. All/any of the three by configuration?
3. Only the `accept-language` header only?

The second option would require configuration.  Something like:

```elixir
pipeline :browser do
  plug Cldr.Plug.Locale, [:accept_language, :query_parameter]
  plug Cldr.Plug.Locale, [:query_parameter]
  plug Cldr,Plug.Locale  # What would the default be?
end
```
Thoughts much appreciated.

**Comment by LostKobrakai** [comment]
I'd vote for keeping it simple and let the plug only do the work, which is unlikely to involve project specifics, so your third option. 

Both a GET param as well as a URL segment will most likely be generated on the backend and can therefore already specify only known cldr languages/locales. So to match one only needs to do `Cldr.known_locale_name?(locale_name)` and can go on with setting the locale to wherever it's needed on success. Any other values are most likely not to be supported anyways. By keeping this in user-land you also don't prescribe the GET param key or the location of the language segment.

The accept header on the other hand is in no situation controlled by the project itself and therefore it does need matching with installed locales, where I'm happy to take a first-party plug implementation.

For the sake of completeness I'll also include my thoughts on what the plug should do with a matched locale, when we talked about it on slack.

> Yeah, I’d imagine the best solution would probably be to have your plug parse the header and put the resulting language tag into the private area of `conn`. Then supply a `Cldr.YourPlug.get_parsed_locate(conn)` for people to retrieve it. Setting that locale as the default locale I’d make the default, but disableable (e.g. I also use the concept of a language set by the user).
> And for gettext I’d maybe supply a way to get the best match, but not a plug to do anything. That I’d leave for documentation

**Comment by danschultzer** [comment]
I would prefer the second option, with a default configuration that goes `already assigned` -> `query parameter` -> `accept language` -> `default locale`, and with an option for custom strategies. The locale might be set as a cookie or in the session. If there's authentication in the app, it'll often be part of the user struct and it'll either be found in the session or directly set in the plug when the user struct has been loaded.

**Comment by kipcole9** [comment]
@LostKobrakai, @danschultzer Thanks for the feedback. I have added two plugs to the master branch (untested):

* `Cldr.Plug.AcceptLanguage` only parses the accept language header, does a "best match" and sets a private key in the conn

* `Cldr.Plug.SetLocale` is more "full featured" and will set the locale for cldr and/or gettext from a locale specified in the accept-language, url, query or body params (configurable).

My sense is that both of the views you have expressed are representative of the two common expectations.  Since the plugs only invoke code that is core in `Cldr` anyway I am not creating any additional technical debt.  Perhaps I am being naive :-)

I will work on tests and documentation over the weekend but as always I appreciate your feedback on the API and the intent.

**Comment by LostKobrakai** [comment]
I really like the separation of the two. The second plug could sport retrieval from a session key as well to hit all use-cases I'd expect.

**Comment by kipcole9** [comment]
Good point  - I’ll add the session key option as well.

**Comment by kipcole9** [comment]
I'm closing this issue since the plugs are implemented.  Please feel free to open issues on the plugs if you see any problems or have any requirements that fit in the scope.

I'm going to focus now on documentation only with the aim to push a 1.0-rc-0 by the end of the weekend.
