### ISSUE TITLE
[BUG] Cldr.Normalize.Currency remove or overwrite essential data

### ISSUE THREAD

**Issue by Schultzer** [kipcole9/cldr#25]
Hi @kipcole9,

There is a bug in Cldr.Normalize.Currency

When we normalize the `currencyData.json` we end up with a map but the problem is that some countries have multiple entries of the same currency code for example "PS" [`L2568-L2591`](https://github.com/unicode-cldr/cldr-core/blob/84fbf749dd3067781b032dd168cbc6d863a25934/supplemental/currencyData.json#L2568-L2591) the `JOD` appears twice so when we create a map from that data we get malformed data because an elixir map can only contain unique keys

with these limitation I would recommend that we use Keyword list where we also can preserve the JSON structere.

We get this
```elixir
%{
  ILP: %{from: ~D[1967-06-01], to: ~D[1980-02-22]},
  ILS: %{from: ~D[1985-09-04]},
  JOD: %{from: ~D[1996-02-12], to: ~D[1967-06-01]}
}
``` 

but it should be this

```elixir
[
  JOD: %{from: ~D[1950-07-01], to: ~D[1967-06-01}
  ILP: %{from: ~D[1967-06-01], to: ~D[1980-02-22]},
  ILS: %{from: ~D[1985-09-04]},
  JOD: %{from: ~D[1996-02-12]},
]
```

**Comment by kipcole9** [comment]
Great catch!  i’ll fix today and add a test for this.  Thanks much for the report.

**Comment by kipcole9** [comment]
fixed in master and pushing release candidate 1 now.
