### ISSUE TITLE
ex_cldr 1.1.0 not compiling under elixir 1.6.0-rc.0

### ISSUE THREAD

**Issue by doughsay** [kipcole9/cldr#28]
When trying to compile my app which depends on ex_cldr using Elixir 1.6.0-rc.0, it fails with this message:

```
$ mix deps.clean ex_cldr
* Cleaning ex_cldr
$ mix deps.get
...
$ mix deps.compile ex_cldr
==> ex_cldr
Compiling 2 files (.erl)
Compiling 30 files (.ex)
Generating Cldr for 2 locales named ["en-001", "root"] with a default locale named "en-001"
could not compile dependency :ex_cldr, "mix compile" failed. You can recompile this dependency with "mix deps.compile ex_cldr", update it with "mix deps.update ex_cldr" or clean it with "mix deps.clean ex_cldr"
** (ArgumentError) argument error
    :erlang.get_module_info(Plug.Conn, :deprecated)
    Plug.Conn.__info__/1
    (mix) lib/mix/tasks/xref.ex:335: Mix.Tasks.Xref.load_exports_and_deprecated/1
    (mix) lib/mix/tasks/xref.ex:326: Mix.Tasks.Xref.load_exports_and_deprecated_into_acc/2
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix) lib/mix/tasks/xref.ex:295: anonymous fn/2 in Mix.Tasks.Xref.source_warnings/2
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix) lib/mix/tasks/xref.ex:291: Mix.Tasks.Xref.source_warnings/2
```

**Comment by doughsay** [comment]
I'm not sure what I did, but I fiddled with it enough to where it compiles now... Sorry for the false alarm!

**Comment by kipcole9** [comment]
Chris, thanks.  I can't reproduce it (I test on 1.5, 1.6 and master). Any chance you have the steps to reproduce since I think its an Elixir bug.

I can't track down the relevant code - i think its in the generated `Module.__info__` function which, I assume for now, is calling `:erlang.module_info(Plug.Conn, :deprecated)` which definitely produces the error you saw.   `Plug.Conn.__info__(:deprecated)` works fine however.

Sorry for the inconvenience.

**Comment by doughsay** [comment]
I can't reproduce it anymore.  I ran `mix clean; mix deps.clean --all; rm -rf _build` and just started fresh and everything worked as expected.  No problems here I guess; thanks for looking into it though!

**Comment by kipcole9** [comment]
Understood, thanks much.  Looks like it might be an error produced when modules compiled on different elixir versions - which would explain why its all good after you removed the `_build` directory.  Thanks for following up.

Let me know too if your have any comments or enhancement requests for cldr.
