### ISSUE TITLE
Documentation for 1.3.2 uses `config :cldr` (instead of `config :ex_cldr` ?)

### ISSUE THREAD

**Issue by phtrivier** [kipcole9/cldr#41]
Following https://hexdocs.pm/ex_cldr/readme.html#getting-started, I just installed `cldr` from hex adding this in my `mix.exs`: 

```
{:ex_cldr, "~> 1.0"},
```
This gets me 1.3.2.
The documentation (and the README.md from master) explain to configure with: 

```
config :cldr,
   default_locale: ....
```

However I could not download any locale other than ["en-001", "root"]. After some googling I found that this other way to configure existed: 

```
config :ex_cldr,
   default_locale: ....
```

This seems to work better. Is it just a documentation issue ? Which one should I use ?

**Comment by kipcole9** [comment]
@phtrivier Thanks very much for the catch,  its a documentation bug.  The correct configuration is always on the `:ex_cldr` key (`ex_cldr` being the name of the package as you know).  I will fix on master.  I plan to push version 1.4 this weekend and this will be included.
