### ISSUE TITLE
module Poison is not available

### ISSUE THREAD

**Issue by benperiton** [kipcole9/cldr#44]
When switching to use Jason as the JSON library, I get the following warning:

warning: function Poison.decode!/1 is undefined (module Poison is not available)
  lib/cldr/config/rbnf_config.ex:106

Do I need to include both Posion and Jason as dependencies?

**Comment by kipcole9** [comment]
@benperiton, its not a requirement to define both and I'm bit perplexed that you're getting this error.  Here's my `dev.exs` on my development repo:
```elixir
use Mix.Config

config :ex_cldr,
  locales: ["root", "bs", "pl", "ru", "th", "he", "af"],
  gettext: Cldr.Gettext,
  precompile_number_formats: ["¤¤#,##0.##"],
  precompile_transliterations: [{:latn, :arab}, {:arab, :thai}],
  json_library: Jason

config :ex_cldr, Cldr.Gettext,
  default_locale: "it"
```
It seems like your config key might not be right?  If the key isn't right then the default would apply, which is `Poison`.

**Comment by benperiton** [comment]
Hey,
My config for it is:

```
config :ex_cldr,
  default_locale: "en",
  json_library: Jason
```

If it makes a difference, ex_cldr is not actually a direct dependency, but it comes from 
```
{:ex_money, "~> 1.1"}
```

It's not really a massive issue, I just like my output to be as clean as it can be :)

A fresh clone of https://github.com/benperiton/testexldr and mix deps.get && mix compile results in the warning.

Elixir: 1.6.1
Erlang: 20.2.2

**Comment by kipcole9** [comment]
Ahhh, you raise a good point.

I'll modify Cldr to check for either `Poison` or `Jason` as the default rather than default the default to `Poison`.  If you get my meaning.  That will mean Cldr and Money will default correctly since Money's default `json_library` is Cldr's default.

**Comment by kipcole9** [comment]
As of [this commit to master](https://github.com/kipcole9/cldr/commit/66cc8ace9cddcb31f030acb80dda78dba4f38d85) `Cldr` now autodetects the presence of either Jason (preferred) or Poison and sets the default `:json_library` accordingly.  

Using the config key `:json_library` can be used as usual to configure any library that implements a `decode!/1` function.

**Comment by kipcole9** [comment]
This commit will be in Cldr 1.4.1 which I aim to have out in the next 24 hours.

**Comment by benperiton** [comment]
Great, thanks!
