### ISSUE TITLE
Fails to compile with Distillery supplied logger level

### ISSUE THREAD

**Issue by erikreedstrom** [kipcole9/cldr#62]
We recent ran into an issue with compilation and ex_cldr as it concerns Logger during compilation.

Our production release uses the following config format, as specified by [distillery](https://hexdocs.pm/distillery/getting-started.html#application-configuration):

```elixir
config :logger, level: :"${LOG_LEVEL}"
```

When ex_cldr installs locales at compile time, it uses the `Logger` to output the message. However, at this point, the config value is `:"${LOG_LEVEL}"`, rather than an atom value expected by the logger. This results in the following error:

```elixir
== Compilation error in file lib/cldr.ex ==
       ** (FunctionClauseError) no function clause matching in Logger.level_to_number/1
       
       The following arguments were given to Logger.level_to_number/1:
       
       # 1
       :"${LOG_LEVEL}"
       
       Attempted function clauses (showing 4 out of 4):
       
       defp level_to_number(-:debug-)
       defp level_to_number(-:info-)
       defp level_to_number(-:warn-)
       defp level_to_number(-:error-)
       
       (logger) lib/logger.ex:492: Logger.level_to_number/1
       (logger) lib/logger.ex:489: Logger.compare_levels/2
       (logger) lib/logger.ex:615: Logger.bare_log/3
       lib/cldr/install.ex:90: Cldr.Install.do_install_locale_name/2
       (elixir) lib/enum.ex:737: Enum."-each/2-lists^foreach/1-0-"/2
       (elixir) lib/enum.ex:737: Enum.each/2
       lib/cldr/install.ex:25: Cldr.Install.install_known_locale_names/0
       lib/cldr.ex:43: (module)
```

Here is the specific line: https://github.com/kipcole9/cldr/blob/master/lib/cldr/install.ex#L90

**Comment by kipcole9** [comment]
Apologies for the inconvenience.  I have [pushed version 1.6.1](https://hex.pm/packages/ex_cldr) with a version that I believe will fix this.  I changed the `Logger` calls in `Cldr.Install.install_locale/1` to use `Logger.bare_log/3` instead of the `Logger` macros.  Please let me know if this does not resolve the issue for you.

**Comment by erikreedstrom** [comment]
@kipcole9 The issue still exists. Note in the stack above, it calls through `bare_log`. The problem seems to be in the Logger `__should_log__` inspection. When this happens, it always checks the config value in the compare function. ☹️ 

Don't see much of an alternative, other than using `__do_log__` directly. 😕
