### ISSUE TITLE
:priv_dir files from a sibling dependency get deleted using cldr compiler

### ISSUE THREAD

**Issue by epilgrim** [kipcole9/cldr#78]
First of all, thanks for the useful lib!!!

I've been chasing this bug on production, where my monitoring tool (appsignal) stopped reporting data, and it was because on compile time, appsignal downloads some files.
```
# relevant part of mix compile --force
Generated sylar app
-----> appsignal on: before deps.clean
       Directory /tmp/build_5ef2fa06241626cf7c9113fb77ca137a/_build/prod/lib/appsignal/priv
       appsignal-agent
       appsignal.architecture
       appsignal_extension.so
       appsignal.h
       appsignal.version
       cacert.pem
       libappsignal.a
```
It turns out, after the compile step is done, those files are not there anymore. They get deleted.
But, if I change my configuration from:
`      compilers: [:phoenix, :gettext] ++ Mix.compilers() ++ [:cldr],`
to
`      compilers: [:phoenix, :gettext] ++ Mix.compilers(),`
the files stay there.

Extrangely, this does not happen on my local machine, not even compiling in prod environment. But it does happen 100% of the time on heroku and my staging servers (normal docker setup)

Can you shed any light on this? how can I help on the debug?

**Comment by kipcole9** [comment]
Wow, that is, ... unexpected.  Sorry for the inconvenience.  There was an issue related to how Heroku builds work (I'll revisit what it was) but it didn't have this symptom.  And I've reviewed the `:cldr` compiler code again and it doesn't do any mutations except `Kernel.ParallelCompiler.compile_to_path(sources, build_dir)` to compile selected files and it does also delete the old versions.  It has no awareness of any other app or dependency much less another deps `:priv_dir`.

I would have said this looks to be Heroku specific but you also said its the same issue in Docker.

There is not doubt the whole `:cldr` compiler thing is huge kludge and `ex_cldr version 2` will remove its need.  But thats no help to you now.

The reason that the `:cldr` compiler exists at all is that it allows CLDR to pick up the locales defined in `Gettext`.  One workaround would potentially be to:

1. Ensure that the locales you have in Gettext are also in configured in Cldr
2. Remove the `:cldr` compiler as you are now doing

I think this will result in a consistent configuration - it just means you will need to manually adjust it if you add additional `Gettext` locales.

Other than that I will need to do some digging into this on the weekend.  Sorry I don't have any more concrete answer for now to what is a very strange situation!

**Comment by epilgrim** [comment]
it was though, but i finally have a repo that reproduces the issue:
https://github.com/epilgrim/test_cldr

the key is in the `build_embedded: true,` parameter in the mix.exs file. 
When it's false, the files are printed at the end of the compile steps
When it's true, the files disappear after compilation

**Comment by kipcole9** [comment]
Thanks incredibly helpful, thank you.  I still don't know what the files disappear but its a huge hint for where to go looking.  Thanks very much for diving into this.  I'll see if I can work it out tonight my time (its early morning now).

**Comment by kipcole9** [comment]
Hmmm, maybe found a cause.  In the cldr compiler task i need to [work out which modules to recompile](https://github.com/kipcole9/cldr/blob/master/lib/mix/tasks/compile.cldr.ex#L160-L174).  That in turns needs to [work out who the callers are](https://github.com/kipcole9/cldr/blob/master/lib/mix/tasks/compile.cldr.ex#L176-L189) which includes the line:
```elixir
  defp callers(dep) do
    try do
      Mix.Dep.in_dependency(dep, fn _module ->
        Mix.Project.build_structure()  # <---- This appears to recreate the structure for each dep

        calls()
        |> Enum.filter(&compile_module?/1)
        |> Enum.map(fn callee -> {dep.app, callee} end)
      end)
      ....
  end
```
And it appears that `Mix.Project.build_structure()` will rebuild the project structure for each dependency and therefore will clear out the `:priv_dir`.

I need to test this supposition but it looks like this is the clearest possibility for now.  Testing tonight and hopefully a fix by morning if this turns out to be the issue.  Thanks for your patience.

**Comment by kipcole9** [comment]
I have created a branch with the `Mix.Project.build_structure()` commented out and in a quick test on your test app (and mine) it seems to compile and recompile correctly without deleting sibling `:priv_dir`.  

Would you consider giving this a try?  Configure with:
```elixir
def deps do
  [
    {:ex_cldr, git: "https://github.com/kipcole9/ex_cldr", branch: "issue_78"},
    ...
  ]
end
```
Let me know if that solves it for you?

**Comment by epilgrim** [comment]
using your branch issue_78 the issue seems resolved. Do you remember why the build_structure() got there in the first place?

**Comment by kipcole9** [comment]
No, I don't remember the reason why its there.  Clearly its a bug to `build_structure/1` on *every* dependency and I know there was a reason I added it at some point.  But the code to work out what needs recompiling went through several iterations and still has conditional compilation depending on what version of Elixir is running so perhaps its a legacy of that.

I need to do some more testing to have confidence that I'm not breaking something but I aim to publish a new version to hex before the end of the weekend.  Hope thats ok.
