### ISSUE TITLE
Replace phoenix dependency with just plug

### ISSUE THREAD

**Issue by LostKobrakai** [kipcole9/cldr#84]
I'm not sure if phoenix is currently used elsewhere besides the tests (github showed 48 pages of searchresults), but if not we should probably replace it with just plug. No need to recompile cldr if just phoenix is updated.

**Comment by kipcole9** [comment]
Its just there as an `:optional` dependency for tests of the `set_locale` plug in a Phoenix router config.   So it shouldn't affect client applications that don't use Phoenix?

**Comment by LostKobrakai** [comment]
Yeah, but I just noticed (because of the 1.4 switch) that cldr is recompiled if the phoenix version is changed. Sure not a big deal, but if plug is enough I'd just depend on that.

**Comment by kipcole9** [comment]
I've changed it to be `only: :test` which might help.  I don't think I can pull `Phoenix.Router` separately from `phoenix`. I'll see if this config change reduces the recompilation in `:dev` at least.

**Comment by LostKobrakai** [comment]
I'll see if I can maybe change the tests for the plug to not need `Phoenix.Router` at some time.

**Comment by kipcole9** [comment]
Version [2.0.0-rc.0](https://github.com/kipcole9/cldr/tree/v2.0) should be out this weekend so that would be the better target if you're up for any contributions.  Mostly documentation updates required now (updates for cldr, cldr_numbers, cldr_currencies and money to be RC first).
