### ISSUE TITLE
Gettext get_locale different from get_cldr_locale

### ISSUE THREAD

**Issue by Cochonours** [kipcole9/cldr#88]
I just added cldr as a dependency as it great to handle proper i18n, and after configuring I still cannot get it to work well with Gettext.

In config.exs, I put:
```
config :gettext,
  default_locale: "fr",
  locales: ~w(fr en es ko)

config :ex_cldr,
  default_locale: "fr", # necessary only for router "default: Cldr.default_locale,"
  gettext: TotoWeb.Gettext,
  json_library: Jason
```

In router.exs, I added the SetLocale plug:
```
    plug Cldr.Plug.SetLocale,
      apps: [:cldr, :gettext],
      from: [:path, :cookie, :accept_language],
      param: "locale",
      default: Cldr.default_locale,
      gettext: TotoWeb.Gettext
```

Per the doc, by adding the :gettext to that "apps" list, the plug should set the locale for gettext, but in my view `Gettext.get_locale()` remains the default "fr", whereas `Cldr.Plug.AcceptLanguage.get_cldr_locale(@conn)` is updated correctly.

Did I miss something? Do I have to set the locale manually for gettext after the setLocale plug?

**Comment by kipcole9** [comment]
Apologies for the inconvenience. The intent is as you describe for that configuration - it should set the `Gettext` locale as well.  I'll look into this in the next 12 hours.

**Comment by kipcole9** [comment]
When `Cldr.Plug.SetLocale` sets a locale for `Gettext` it sets it as the locale *for the specified backend*.  In your case, `TotoWeb.Gettext`.  I believe if you change `Gettext,get_locale()` to `Gettext.get_locale(TotoWeb.Gettext)` you will see the change.

I will update the documentation to reflect this.

There still remains the open question as to whether this plug should set the global `Gettext` locale or not.  My preference is *not* but I'm open to thoughts on the matter.

Would you let me know if this solves your issue?

**Comment by Cochonours** [comment]
Thanks for having a look! Indeed it works when I specify the backend. Could you tell me how to configure it to set it globally?

**Comment by LostKobrakai** [comment]
I'm just curious, but why should a http request change the global locale? I mean concurrent requests would override each other, which I doubt is what the plug is supposed to do.

**Comment by kipcole9** [comment]
I believe @Cochonours means "set the locale for the current process for all backends".

On re-reading the `Gettext` docs I see (emphasis is mine):

> Gettext.put_locale/1 can be used to change the locale of all backends for the current Elixir process. That’s the **preferred mechanism for setting the locale at runtime**. Gettext.put_locale/2 can be used when you want to set the locale of one specific Gettext backend without affecting other Gettext backends.

Which suggests `Cldr.Plug.SetLocale` should really set the locale using `put_locale/1` as the default behaviour rather than `put_locale/2` which is  the current behaviour. And an option to set using `put_locale/2` if required.

**Comment by kipcole9** [comment]
What I propose doing, and only for Cldr version 2.0, is the following:

Today, Cldr 1.x, the `:apps` config key is a list of atoms like:
```
apps: [:gettext, :cldr]
```
In Cldr 2.0 the behaviour will change for this configuration to set the per-process locale for all backends for both `Cldr` and `Gettext`.  This aligns with `Gettext` preferred behaviour and `Cldr` will follow.

In Cldr version 2.0 the configuration will support an alternative keyword list version:
```
apps: [gettext: :all, cldr: <backend_module>]
```
That is, each app can set either (per-process) locale for all backends, or the only the `backend` specific one.

Comments welcome.

**Comment by kipcole9** [comment]
As of [this commit](https://github.com/kipcole9/cldr/commit/abb187a50f6c52ecab6800d7fc1c30a741fadf50) the behaviour of Cldr now more closely matches that of Gettext.

**Comment by Cochonours** [comment]
> I believe @Cochonours means "set the locale for the current process for all backends".
Indeed!

Thanks for your update.
