### ISSUE TITLE
Code.LoadError with 2.x

### ISSUE THREAD

**Issue by robotvert** [kipcole9/cldr#93]
Hi,

I'm not sure if this is coming from ex_cldr_numbers or ex_cldr itself but upgrading to 2.x makes my phoenix not compile anymore with Code.LoadError raised randomly (e.g. the error below happens in different files upon several `mix compile` runs)

`mix compile`:
```
== Compilation error in file lib/decapx_web/controllers/pdf_controller.ex ==
** (Code.LoadError) could not load /Users/julien/dev/repos/decapx/deps/postgrex/lib/decapx_web/controllers/pdf_controller.ex
    (elixir) lib/code.ex:1147: Code.find_file/2
    (elixir) lib/code.ex:928: Code.compile_file/2
    (elixir) lib/kernel/parallel_compiler.ex:206: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```

iex gives a bit more info (note the different file):
`iex -S mix`
```
== Compilation error in file lib/decapx/works/chantier.ex ==
** (Code.LoadError) could not load /Users/julien/dev/repos/decapx/deps/ex_cldr/lib/decapx/works/chantier.ex
    (elixir) lib/code.ex:1147: Code.find_file/2
    (elixir) lib/code.ex:928: Code.compile_file/2
    (elixir) lib/kernel/parallel_compiler.ex:206: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
** (MatchError) no match of right hand side value: {:error, :bad_directory}
    (mix) lib/mix/tasks/compile.all.ex:24: anonymous fn/1 in Mix.Tasks.Compile.All.run/1
    (mix) lib/mix/tasks/compile.all.ex:39: Mix.Tasks.Compile.All.with_logger_app/1
    (mix) lib/mix/task.ex:316: Mix.Task.run_task/3
    (mix) lib/mix/tasks/compile.ex:94: Mix.Tasks.Compile.run/1
    (mix) lib/mix/task.ex:316: Mix.Task.run_task/3
    (mix) lib/mix/tasks/app.start.ex:57: Mix.Tasks.App.Start.run/1
    (mix) lib/mix/task.ex:316: Mix.Task.run_task/3
    (mix) lib/mix/tasks/run.ex:129: Mix.Tasks.Run.run/5
    (mix) lib/mix/tasks/run.ex:85: Mix.Tasks.Run.run/1
    (mix) lib/mix/task.ex:316: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
    (elixir) lib/code.ex:767: Code.require_file/2
```
Here are the differences from 1.x to 2.x:

`config/config.exs`
```diff
-config :ex_cldr,
-  default_locale: "fr",
-  locales: ["fr"]
```

`lib/decapx/cldr.ex`
```diff
+defmodule Decapx.Cldr do
+  use Cldr,
+    default_locale: "fr",
+    locales: ["fr"]
+end
```

`mix.exs`
```
-      {:ex_cldr_numbers, "~> 1.0"},
+      {:ex_cldr_numbers, "~> 2.0"},
```

and where I'm using it, the difference is simply `Cldr.Number.to_string` becoming `Decapx.Cldr.Number.to_string`.

Looking around, I found this [issue](https://github.com/elixir-lang/elixir/issues/7699) that looks somewhat similar but it looks like it's been resolved.

Also, I wonder if I need to keep cldr in the compilers list, e.g.
```
compilers: [:phoenix, :gettext] ++ Mix.compilers() ++ [:cldr],
```
(keeping it as is or removing it didn't make any difference)

Running "Erlang/OTP 21 [erts-10.1.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]" and Elixir 1.7.4.

Let me know if you need more info, thanks!

**Comment by robotvert** [comment]
Yeah as expected this didn't help much for this case, glad a bug has been unearthed and resolved though!

Here's my mix.exs file:

```elixir
defmodule Decapx.MixProject do
  use Mix.Project

  def project do
    [
      app: :decapx,
      version: "0.1.0",
      elixir: "~> 1.6",
      elixirc_paths: elixirc_paths(Mix.env()),
      compilers: [:phoenix, :gettext] ++ Mix.compilers(),
      start_permanent: Mix.env() == :prod,
      aliases: aliases(),
      deps: deps()
    ]
  end

  def application do
    [
      mod: {Decapx.Application, []},
      extra_applications: [:logger, :runtime_tools]
    ]
  end

  # Specifies which paths to compile per environment.
  defp elixirc_paths(:test), do: ["lib", "test/support"]
  defp elixirc_paths(_), do: ["lib"]

  defp deps do
    [
      # Phoenix and friends
      {:phoenix, "~> 1.4.0"},
      {:phoenix_pubsub, "~> 1.1"},
      {:phoenix_ecto, "~> 4.0"},
      {:ecto_sql, "~> 3.0"},
      {:postgrex, ">= 0.0.0"},
      {:gettext, "~> 0.11"},
      {:jason, "~> 1.0"},
      {:plug_cowboy, "~> 2.0"},

      {:cachex, "~> 3.0"},
      {:cors_plug, "~> 2.0"},
      {:decimal, "~> 1.4"},
      {:distillery, "~> 2.0", runtime: false},
      {:ex_cldr_numbers, "~> 2.0"},
      {:money, "~> 1.3"},
      {:apex, "~> 1.0", only: [:dev, :test]},
      {:credo, "~> 1.0", only: :dev, runtime: false},
      {:benchee, "~> 0.9", only: :dev},
      {:sobelow, "~> 0.5", only: :dev}
    ]
  end

  defp aliases do
    [
      "ecto.setup": ["ecto.create", "ecto.migrate", "run priv/repo/seeds.exs"],
      "ecto.reset": ["ecto.drop", "ecto.setup"]
      #  test: ["ecto.create --quiet", "ecto.migrate", "test"]
    ]
  end
end
```

The config files I have have nothing special about them, let me know if you need those too.

**Comment by kipcole9** [comment]
Hmmm, thats very strange.  But appreciate the `mix.exs` which I think will allow me to recreate enough of your environment to work out what the issue might be during compilation.  I'll work on this over the next 24 hours and report what I find.

**Comment by kipcole9** [comment]
I have created a test app that uses your `mix.exs` except it doesn't start an application, or have a repo yet either.  It has only a default config for Cldr.  

I expected I would get errors during compilation based upon your initial report but I have not seen any.

If you have the patience, perhaps you could clone this repo and just plain `iex -S mix`?  It worked with no issues for me.  If it works for you too then I'll have to look elsewhere by incrementally adding in an ecto repo etc etc etc.
```
git clone https://github.com/kipcole9/decapx_test.git
cd decapx_test
iex -S mix
```

**Comment by kipcole9** [comment]
In relooking at the error messages again I'm seeing from your examples:
```
** (Code.LoadError) could not load /Users/julien/dev/repos/decapx/deps/postgrex/lib/decapx_web/controllers/pdf_controller.ex

** (Code.LoadError) could not load /Users/julien/dev/repos/decapx/deps/ex_cldr/lib/decapx/works/chantier.ex
```
And these are clearly bogus paths and very strange.  I think I may have an understanding of why this can happen and will have to think on how to remediate it.

**Comment by kipcole9** [comment]
As of [this commit](https://github.com/kipcole9/cldr/commit/394dc98a7ee1c45bd3babefd6cc210d265dd611f) I believe the issue is resolved.  The [changelog](https://github.com/kipcole9/cldr/blob/v2.0.4/CHANGELOG.md) has further detail.

It is also on `hex` as [ex_cldr version 2.0.4](https://hex.pm/packages/ex_cldr/2.0.4)

Sorry for the inconvenience.  Definitely a case of trying to be too clever for my own good.  And of course please let me know if in fact the issue is resolved for you (or not).

**Comment by robotvert** [comment]
Confirmed this solved it! Thanks!!
